name: Build Linux Live ISO

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update and upgrade packages
      run: |
        sudo apt update
        sudo apt upgrade -y

    - name: Install build dependencies
      run: |
        sudo apt install -y wget make gawk gcc bc bison flex xorriso libelf-dev libssl-dev

    - name: Build Linux Live ISO
      run: |
        ./src/build_minimal_linux_live.sh
